before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - java -version
  - ant -version
  - cd benchmarks
  - touch local.properties
  - echo "make=/usr/bin/make" >> local.properties
  - echo "build.failonerror=true" >> local.properties
  - echo "jdk7home=/usr/lib/jvm/java-7-openjdk-amd64" >> local.properties
  - echo "jdk9home=/usr/lib/jvm/java-9-openjdk-amd64" >> local.properties
  - cat local.properties

avrora:
  script:
    - ant -Dbuild.target-jar=dacapo.jar avrora
    - java -jar dacapo.jar avrora

batik:
  script:
    - ant -Dbuild.target-jar=dacapo.jar batik
    - java -jar dacapo.jar batik

eclipse:
  script:
    - ant -Dbuild.target-jar=dacapo.jar eclipse
    - java -jar dacapo.jar eclipse

fop:
  script:
    - ant -Dbuild.target-jar=dacapo.jar fop
    - java -jar dacapo.jar fop

h2:
  script:
    - ant -Dbuild.target-jar=dacapo.jar h2
    - java -jar dacapo.jar h2

jython:
  script:
    - ant -Dbuild.target-jar=dacapo.jar jython
    - java -jar dacapo.jar jython

luindex:
  script:
    - ant -Dbuild.target-jar=dacapo.jar luindex
    - java -jar dacapo.jar luindex

lusearch:
  script:
    - ant -Dbuild.target-jar=dacapo.jar lusearch
    - java -jar dacapo.jar lusearch

pmd:
  script:
    - ant -Dbuild.target-jar=dacapo.jar pmd
    - java -jar dacapo.jar pmd

sunflow:
  script:
    - ant -Dbuild.target-jar=dacapo.jar sunflow
    - java -jar dacapo.jar sunflow

tomcat:
  script:
    - ant -Dbuild.target-jar=dacapo.jar tomcat
    - java -jar dacapo.jar tomcat

tradebeans:
  script:
    - script -q -c "ant -Dbuild.target-jar=dacapo.jar tradebeans" script.out
    - sleep 120 | script -q -c "java -jar dacapo.jar tradebeans" script.out

tradesoap:
  script:
    - script -q -c "ant -Dbuild.target-jar=dacapo.jar tradesoap" script.out
    - sleep 120 | script -q -c "java -jar dacapo.jar tradesoap" script.out

xalan:
  script:
    - ant -Dbuild.target-jar=dacapo.jar xalan
    - java -jar dacapo.jar xalan
